name: proof-html

on:
  push:
    paths:
      - '**/*.html'
      - '.github/workflows/proof-html.yml'
  pull_request:
    paths:
      - '**/*.html'
      - '.github/workflows/proof-html.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: proof-html-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate HTML proofs
        uses: anishathalye/proof-html@v2
        with:
          directory: ./
